### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by lakizuru** [lakizuru/streetlamp-frontend#4]
Add the following image as the favicon to the dashboard. @nisalrenuja
![Logo](https://user-images.githubusercontent.com/30179271/137132365-9193ccff-b008-4904-af32-40b84392d91e.png)

**Comment by B1TSH3LL** [comment]
just add label hacktoberfest-accepted

**Comment by ananya224** [comment]
Hey, may I do it ?

**Comment by lakizuru** [comment]
Favicon fixed
